### ISSUE TITLE
People Page

### ISSUE THREAD

**Issue by mariuscoto** [rosedu/hub#30]
Add a page that displays all the people of ROSEdu that have logged in the app.

TODO:

- [x] add a link to the page in the navigation bar, named **People**
- [x] add a new route (/people) that lists all the members that have @rosedu email addresses, together with their full name, avatar and email address. They should be listed in alphabetically order, by name.
- [x] when you click on a user's name, you should be redirected to his profile page, a page that contains all informations about him. When a user (logged in) accesses his own profile, he can edit it (add more informations), through an **Edit Button**; the profile page is accessible at /people/EMAIL_HANDLE (e.g. /people/marius)
- [ ] the edit button fires up a new page where a user can add links to his social accounts (fb, tw, in); this page is accesible at /people/USER/edit and can be accessed just by the corresponding user
- [ ] on the events page, replace the currently logged in user name with a link to his profile page
- [ ] the contact person of each event is also a link to the user's profile page

**Comment by mihneadb** [comment]
This issue needs to be updated. Some of the stuff is live.
